source ~/.local/share/umaku/defaults/zsh/rc

export ZSH="$HOME/.oh-my-zsh"

export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"

plugins=(
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# vi mode
bindkey -v
export KEYTIMEOUT=1
