export ZSH="$HOME/.oh-my-zsh"

export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"
export TERM=xterm-256color

plugins=(
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# vi mode
bindkey -v
export KEYTIMEOUT=1

source ~/.local/share/umaku/defaults/zsh/rc
